spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/todoticket_db
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
  # jpa:
    # hibernate.ddl-auto: update
    # generate-ddl: true
    # show-sql: true